### ISSUE TITLE
support custom information content 

### ISSUE THREAD

**Issue by justaddcoffee** [monarch-initiative/semsimian#124]
Currently we are calculating `ic_map` using the structure of the ontology. That is, the IC for any term is based on the number of times the term or its descendants occurs in the ontology, using for example subject-predicate-object (SPO) data 

For some use cases, it would be helpful to allow this to be based on counts that were observed in a population. For example, [the HPOA file](https://hpo.jax.org/app/data/annotations) provides the number of times a given phenotype was observed in the population of all patients with any disease described in that file. 

So, I think what we'd need would be some method in Semsimian that supports reading counts / IC values for all ontology terms of interest directly into `ic_map`

@hrshdhgd does this make sense

@julesjacobsen is this an accurate description of what would be useful?

**Comment by matentzn** [comment]
I checked with @cmungall and I think that the idea is this:

1. Decouple IC score computation from semantic similarity computation
2. There is a [command in OAK, runoak information-content](https://incatools.github.io/ontology-access-kit/guide/similarity.html#information-content) which allows you to compute IC scores against an ontology while passing in annotation tables. 

Would it make sense to consolidate all work on IC score in that OAK command instead of working out a way to do this in semsimian itself?

**Comment by hrshdhgd** [comment]
The real question is would it make sense to redo oak in rust ... I'd say YES PLEASE! lol

**Comment by matentzn** [comment]
Oh ok, I didnt know that - I always assumed this was purely about jaccard. 

In any case - it does not matter where the source of truth is for the implementation. I just want to make sure that there is 1 implementation, that it can be accessed in oak (wrapping semsimian), and that it is clearly documented how to use it.. But the point about decoupling still stands - shouldnt there be two distinct methods for pairwise sim and IC score computation?

**Comment by hrshdhgd** [comment]
IC score is calculated and stored as a cache in semsimian the moment a `Semsimian` object is created. So decoupling already exists.
