### ISSUE TITLE
standardizing and documenting release process: why is `release` under qc.yml?

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/semsimian#43]
it looks like any time we merge a PR onto main there is a release to PyPI?

https://github.com/monarch-initiative/semsimian/blob/3b6535241f1a872cca0d1e554229c02caa30549a/.github/workflows/qc.yml#L107-L123

**Comment by cmungall** [comment]
It looks like we make wheels for every PR. While I guess this is OK for testing it's quite expensive - especially for mac:

https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#per-minute-rates

**Comment by caufieldjh** [comment]
A couple TODOs, then:

- [ ] Separate release step from qc steps
- [ ] Restrict release to its own trigger (manual and/or upon version change or GH release; rather than on push to main)
- [ ] Restrict full set of test conditions to pre-release only (rather than on all commits)
- [ ] Document workflow in README
