### ISSUE TITLE
Add method `semsimian embedding-similarity` to semsimian

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/semsimian#74]
We should implement a method for computing a semantic similarity profile from an embedding.

Input:

- `--embedding` (a TSV file where the first column is an identifiers, and all subsequent columns describe the embedding (numbers)).
- `--similarity-measure` (or whatever semsimian calls this), default `cosine`.
- the options for streaming writing etc, see #73 
- the usual options for selecting terms

Output:

A semantic similarity profile according to the oak-semsim standard (slightly reduced, as there is no IC or anything computed).

@caufieldjh can you link to an example embedding (does not matter about what).

@hrshdhgd can you take this on?

**Comment by caufieldjh** [comment]
> can you link to an example embedding (does not matter about what).

Sure - this is what First Order LINE node embeddings for RO look like: https://kg-hub.berkeleybop.io/embeddings/ro_firstorderline_test.tsv

**Comment by hrshdhgd** [comment]
Is this always going to be `dimension == 100` ?

**Comment by justaddcoffee** [comment]
I think dimension will not necessarily always be 100

For the embeddings Nico asked for, we maybe could do deepwalk/skipgram embeddings?

**Comment by matentzn** [comment]
I agree with all, generall, same architecture as the normal semsimian similarity command!

**Comment by hrshdhgd** [comment]
Question: Is the `cosine_similarity` spit out as a separate output file of should it be an additional column in the existent output for the `similarity` command in `oaklib`?

**Comment by caufieldjh** [comment]
It makes sense to me to include cosine_similarity among the other similarity scores, though [it isn't in the OAK datamodel.](https://github.com/INCATools/ontology-access-kit/blob/main/docs/datamodels/similarity/score.md)

**Comment by caufieldjh** [comment]
Here's first-order LINE of BFO:
https://pastebin.com/EgBxpsNX

**Comment by hrshdhgd** [comment]
Ok, I have a new `oak` pre-release and it calculates `cosine_similarity`

- Create a new virtual env
- `pip install oaklib==0.5.13rc2`
- `runoak -i semsimian:sqlite:obo:bfo similarity -p i BFO:0000040 @ BFO:0000002 --low-memory --embeddings-file path-to -the-tsv-Harry-linked-above` (BFO embeddings)

This generates 2 files
- `similarity_map.tsv`
- `similarity_map_filled.tsv` - This because `--autolabel` == True (by default)

The second file looks like this
| subject_id  | object_id  | jaccard_similarity | ancestor_information_content | phenodigm_score | cosine_similarity | ancestor_id  | _inherited_slots | subject_label | subject_source | object_label | object_source | ancestor_label | ancestor_source | object_information_content | subject_information_content | dice_similarity |
|-------------|------------|--------------------|-----------------------------|-----------------|-------------------|--------------|------------------|---------------|----------------|--------------|----------------|----------------|-----------------|----------------------------|----------------------------|-----------------|
| BFO:0000040 | BFO:0000002 | 0.5                | 0.4854268271702417          | 0.4926595311014706 | 0.09582515104047208 | BFO:0000002  |                  | material entity |                | continuant   |                | continuant     |                 |                            |                            |                 |

**Comment by matentzn** [comment]
Excellent @hrshdhgd!

@souzadevinicius can you test this in the semantic similarity profile registry?
