### ISSUE TITLE
Add option to read closure file from a sqlite3 database

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/semsimian#75]
Sometimes passing a closure table from python can take a long time.

Add an option to read from a sqlite database. The tables can be ignored except for `entailed_edge`

https://incatools.github.io/semantic-sql/EntailedEdge

**Comment by hrshdhgd** [comment]
So basically `oaklib` passes just the path of the `sqlite` db file for `semsimian` to query for entailed edges.

**Comment by hrshdhgd** [comment]
Here are my thoughts, The `Semsimian` object creation in `oaklib` via `semsimian` right now is 
```
self.semsimian = Semsimian(spo, self.term_pairwise_similarity_attributes)
```

I'm going to make it such this the following is also possible:
```
self.semsimian = Semsimian(predicates, self.term_pairwise_similarity_attributes)
```
That way based on the `predicates` passed, `spo` is created on the `semsimian` side of things rather than expecting it from `oaklib`. 

Before I start wiring things, I have a question:
- Does this mean I duplicate the [`relationships()`](https://github.com/INCATools/ontology-access-kit/blob/0d9cd547ba7badf0e17a5f467a3aefeccdca673b/src/oaklib/implementations/sqldb/sql_implementation.py#L839-L943) function in `SQLImplementation`?

**Comment by cmungall** [comment]
I think your q is answered and this is handled - 
can we close this now?

**Comment by hrshdhgd** [comment]
Yes sir!
